import crypto from 'crypto';
import {
  Company,
  Department,
  User,
  Role,
  PermissionCode,
  FormTemplate,
  NumberingRule,
  DocumentRecord,
  AuditLog,
  FormField,
} from '../src/types/index.js';

class InMemoryStore {
  public companies: Company[] = [];
  public departments: Department[] = [];
  public roles: Role[] = [];
  public users: User[] = [];
  public numberingRules: NumberingRule[] = [];
  public formTemplates: FormTemplate[] = [];
  public documents: DocumentRecord[] = [];
  public auditLogs: AuditLog[] = [];

  constructor() {
    this.seedInitialData();
  }

  private seedInitialData() {
    // 1. Companies
    this.companies = [
      {
        id: 'comp-gwds',
        name: 'Gulf Way Delivery Services LLC',
        code: 'GWDS',
        tradeLicenseNumber: 'CN-1084920',
        logoUrl: '',
        stampUrl: '',
        address: 'Al Quoz Industrial Area 3, Warehouse 14, Dubai, UAE',
        phone: '+971 4 394 8820',
        email: 'operations@gulfwaydelivery.ae',
        status: 'ACTIVE',
        createdAt: '2026-01-10T08:00:00.000Z',
        updatedAt: '2026-01-10T08:00:00.000Z',
      },
      {
        id: 'comp-gwt',
        name: 'Gulf Way Transport LLC',
        code: 'GWT',
        tradeLicenseNumber: 'CN-1073841',
        logoUrl: '',
        stampUrl: '',
        address: 'Mussafah Industrial Sector 9, Abu Dhabi, UAE',
        phone: '+971 2 554 9912',
        email: 'transport@gulfway.ae',
        status: 'ACTIVE',
        createdAt: '2026-01-15T09:00:00.000Z',
        updatedAt: '2026-01-15T09:00:00.000Z',
      },
      {
        id: 'comp-gwl',
        name: 'Gulf Way Logistics & Express LLC',
        code: 'GWL',
        tradeLicenseNumber: 'CN-1092834',
        logoUrl: '',
        stampUrl: '',
        address: 'Sharjah Airport International Free Zone (SAIF), Sharjah, UAE',
        phone: '+971 6 526 1140',
        email: 'logistics@gulfway.ae',
        status: 'ACTIVE',
        createdAt: '2026-02-01T10:00:00.000Z',
        updatedAt: '2026-02-01T10:00:00.000Z',
      },
    ];

    // 2. Departments
    this.departments = [
      { id: 'dept-hr', code: 'HR', name: 'Human Resources' },
      { id: 'dept-ops', code: 'OPS', name: 'Fleet & Operations' },
      { id: 'dept-fin', code: 'FIN', name: 'Finance & Accounts' },
      { id: 'dept-adm', code: 'ADM', name: 'General Administration' },
      { id: 'dept-leg', code: 'LEG', name: 'Legal & Compliance' },
    ];

    // 3. System Roles & Granular Permissions
    const allPermissions: PermissionCode[] = [
      'USER_VIEW',
      'USER_CREATE',
      'USER_EDIT',
      'USER_DISABLE',
      'FORM_VIEW',
      'FORM_CREATE',
      'FORM_EDIT',
      'FORM_DELETE',
      'FORM_PUBLISH',
      'DOCUMENT_CREATE',
      'DOCUMENT_VIEW',
      'DOCUMENT_EDIT_DRAFT',
      'DOCUMENT_GENERATE',
      'DOCUMENT_SIGN',
      'DOCUMENT_APPROVE',
      'DOCUMENT_REJECT',
      'DOCUMENT_VOID',
      'DOCUMENT_DOWNLOAD',
      'COMPANY_MANAGE',
      'NUMBERING_MANAGE',
      'AUDIT_VIEW',
      'SETTINGS_MANAGE',
      'COMPANY_STAMP',
    ];

    this.roles = [
      {
        id: 'role-superadmin',
        code: 'SUPER_ADMIN',
        name: 'Super Administrator',
        description: 'Full unrestricted governance, security and system control across all companies',
        isSystem: true,
        permissions: allPermissions,
      },
      {
        id: 'role-companyadmin',
        code: 'COMPANY_ADMIN',
        name: 'Company Administrator',
        description: 'Complete management over company forms, employees, documents and numbering',
        isSystem: true,
        permissions: [
          'USER_VIEW',
          'USER_CREATE',
          'USER_EDIT',
          'FORM_VIEW',
          'FORM_CREATE',
          'FORM_EDIT',
          'FORM_PUBLISH',
          'DOCUMENT_CREATE',
          'DOCUMENT_VIEW',
          'DOCUMENT_EDIT_DRAFT',
          'DOCUMENT_GENERATE',
          'DOCUMENT_SIGN',
          'DOCUMENT_APPROVE',
          'DOCUMENT_REJECT',
          'DOCUMENT_VOID',
          'DOCUMENT_DOWNLOAD',
          'NUMBERING_MANAGE',
          'AUDIT_VIEW',
          'COMPANY_STAMP',
        ],
      },
      {
        id: 'role-formadmin',
        code: 'FORM_ADMIN',
        name: 'Form Template Administrator',
        description: 'Configures forms, drag-and-drop PDF field coordinates and numbering rules',
        isSystem: true,
        permissions: [
          'FORM_VIEW',
          'FORM_CREATE',
          'FORM_EDIT',
          'FORM_DELETE',
          'FORM_PUBLISH',
          'NUMBERING_MANAGE',
          'DOCUMENT_VIEW',
        ],
      },
      {
        id: 'role-approver',
        code: 'APPROVER',
        name: 'Official Approver / Manager',
        description: 'Reviews submitted document records, signs digitally, approves or rejects',
        isSystem: true,
        permissions: [
          'FORM_VIEW',
          'DOCUMENT_VIEW',
          'DOCUMENT_SIGN',
          'DOCUMENT_APPROVE',
          'DOCUMENT_REJECT',
          'DOCUMENT_DOWNLOAD',
          'COMPANY_STAMP',
        ],
      },
      {
        id: 'role-user',
        code: 'USER',
        name: 'Standard Employee / Rider',
        description: 'Browses form catalog, saves drafts, initiates numbering, signs and downloads',
        isSystem: true,
        permissions: [
          'FORM_VIEW',
          'DOCUMENT_CREATE',
          'DOCUMENT_VIEW',
          'DOCUMENT_EDIT_DRAFT',
          'DOCUMENT_GENERATE',
          'DOCUMENT_SIGN',
          'DOCUMENT_DOWNLOAD',
        ],
      },
      {
        id: 'role-auditor',
        code: 'AUDITOR',
        name: 'Compliance Auditor',
        description: 'Read-only inspection of document register, cryptographic hashes and audit history',
        isSystem: true,
        permissions: ['USER_VIEW', 'FORM_VIEW', 'DOCUMENT_VIEW', 'AUDIT_VIEW', 'DOCUMENT_DOWNLOAD'],
      },
    ];

    // 4. Default Seed Users
    this.users = [
      {
        id: 'usr-admin',
        fullName: 'Mohammed Al-Qasimi',
        employeeId: 'EMP-001',
        email: 'superadmin@gulfway.ae',
        phone: '+971 50 112 3344',
        companyId: 'comp-gwds',
        companyIds: ['comp-gwds', 'comp-gwt', 'comp-gwl'],
        departmentId: 'dept-adm',
        designation: 'Managing Director & Super Admin',
        roleId: 'role-superadmin',
        roleName: 'Super Administrator',
        permissions: allPermissions,
        status: 'ACTIVE',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
      },
      {
        id: 'usr-hr-fatima',
        fullName: 'Fatima Al-Zahra',
        employeeId: 'EMP-024',
        email: 'fatima.hr@gulfway.ae',
        phone: '+971 52 884 9123',
        companyId: 'comp-gwds',
        companyIds: ['comp-gwds', 'comp-gwt'],
        departmentId: 'dept-hr',
        designation: 'Head of Human Resources',
        roleId: 'role-companyadmin',
        roleName: 'Company Administrator',
        permissions: this.roles.find((r) => r.id === 'role-companyadmin')!.permissions,
        status: 'ACTIVE',
        createdAt: '2026-01-15T00:00:00.000Z',
        updatedAt: '2026-01-15T00:00:00.000Z',
      },
      {
        id: 'usr-ops-tariq',
        fullName: 'Tariq Mansoor',
        employeeId: 'EMP-056',
        email: 'tariq.ops@gulfway.ae',
        phone: '+971 55 776 4321',
        companyId: 'comp-gwds',
        companyIds: ['comp-gwds'],
        departmentId: 'dept-ops',
        designation: 'Fleet & Operations Manager',
        roleId: 'role-approver',
        roleName: 'Official Approver / Manager',
        permissions: this.roles.find((r) => r.id === 'role-approver')!.permissions,
        status: 'ACTIVE',
        createdAt: '2026-02-01T00:00:00.000Z',
        updatedAt: '2026-02-01T00:00:00.000Z',
      },
      {
        id: 'usr-rider-irfan',
        fullName: 'Mohammed Irfan',
        employeeId: 'RDR-1092',
        email: 'irfan.rider@gulfway.ae',
        phone: '+971 54 332 9988',
        companyId: 'comp-gwds',
        companyIds: ['comp-gwds'],
        departmentId: 'dept-ops',
        designation: 'Senior Fleet Dispatcher / Rider',
        roleId: 'role-user',
        roleName: 'Standard Employee / Rider',
        permissions: this.roles.find((r) => r.id === 'role-user')!.permissions,
        status: 'ACTIVE',
        createdAt: '2026-03-01T00:00:00.000Z',
        updatedAt: '2026-03-01T00:00:00.000Z',
      },
    ];

    // 5. Numbering Rules
    this.numberingRules = [
      {
        id: 'rule-default',
        formTemplateId: 'DEFAULT',
        name: 'Default Enterprise Pattern',
        pattern: '{COMPANY}-{DEPARTMENT}-{FORMCODE}-{YYYY}-{SEQ:6}',
        sequenceReset: 'YEARLY',
        startingSequence: 1001,
        currentSequence: 1045,
        lastResetPeriod: '2026',
        description: 'Standard 6-digit annual sequential numbering engine',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-08T00:00:00.000Z',
      },
      {
        id: 'rule-leave',
        formTemplateId: 'form-leave',
        name: 'HR Leave Application Numbering',
        pattern: '{COMPANY}-HR-LF-{YYYY}-{SEQ:6}',
        sequenceReset: 'YEARLY',
        startingSequence: 1001,
        currentSequence: 1024,
        lastResetPeriod: '2026',
        description: 'Strictly sequential HR leave document tracker',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-08T00:00:00.000Z',
      },
      {
        id: 'rule-salary-advance',
        formTemplateId: 'form-salary-advance',
        name: 'Finance Salary Advance Numbering',
        pattern: '{COMPANY}-FIN-SAF-{YYYY}-{SEQ:6}',
        sequenceReset: 'YEARLY',
        startingSequence: 1001,
        currentSequence: 1018,
        lastResetPeriod: '2026',
        description: 'Audited finance advance voucher sequence',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-08T00:00:00.000Z',
      },
      {
        id: 'rule-bike-handover',
        formTemplateId: 'form-bike-handover',
        name: 'Fleet Vehicle Handover Numbering',
        pattern: '{COMPANY}-OPS-BHF-{YYYY}-{SEQ:6}',
        sequenceReset: 'YEARLY',
        startingSequence: 1001,
        currentSequence: 1055,
        lastResetPeriod: '2026',
        description: 'Fleet asset & vehicle custody numbering rule',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-08T00:00:00.000Z',
      },
      {
        id: 'rule-salary-cert',
        formTemplateId: 'form-salary-certificate',
        name: 'Staff Salary Certificate Register',
        pattern: '{COMPANY}-HR-SSC-{YYYY}-{SEQ:6}',
        sequenceReset: 'YEARLY',
        startingSequence: 1001,
        currentSequence: 1026,
        lastResetPeriod: '2026',
        description: 'Official sequential register for Staff Salary & Employment Certificates',
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-09-08T00:00:00.000Z',
      },
    ];

    // 6. Form Templates with Complete Field Coordinates & Mapping
    const leaveFields: FormField[] = [
      {
        id: 'fld-doc-num',
        name: 'document_number',
        label: 'Official Document Number',
        type: 'document_number',
        pageNumber: 1,
        x: 64,
        y: 6.5,
        width: 30,
        height: 3.2,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-emp-name',
        name: 'employee_name',
        label: 'Employee Full Name',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'e.g. Mohammed Irfan',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-emp-id',
        name: 'employee_id',
        label: 'Employee ID / Rider Code',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'e.g. RDR-1092',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-dept',
        name: 'department',
        label: 'Department',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 34,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        defaultValue: 'Operations',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-desig',
        name: 'designation',
        label: 'Designation / Title',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 34,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'e.g. Dispatch Rider',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-leave-type',
        name: 'leave_type',
        label: 'Leave Category',
        type: 'dropdown',
        pageNumber: 1,
        x: 8,
        y: 40,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        options: ['Annual Leave', 'Sick Leave', 'Emergency Leave', 'Unpaid Leave', 'Bereavement'],
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-leave-days',
        name: 'total_days',
        label: 'Total Leave Days',
        type: 'number',
        pageNumber: 1,
        x: 52,
        y: 40,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '30',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-start-date',
        name: 'start_date',
        label: 'Leave Commencing Date',
        type: 'date',
        pageNumber: 1,
        x: 8,
        y: 46,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-end-date',
        name: 'end_date',
        label: 'Leave Concluding Date',
        type: 'date',
        pageNumber: 1,
        x: 52,
        y: 46,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-contact',
        name: 'contact_number',
        label: 'Contact Number During Leave',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 52,
        width: 84,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '+971 50 000 0000 or international phone',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-reason',
        name: 'leave_reason',
        label: 'Detailed Justification / Reason',
        type: 'textarea',
        pageNumber: 1,
        x: 8,
        y: 58,
        width: 84,
        height: 7,
        fontSize: 9.5,
        required: true,
        placeholder: 'State the specific purpose and travel schedule for this leave request.',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-emp-sig',
        name: 'employee_signature',
        label: 'Applicant Signature',
        type: 'signature',
        pageNumber: 1,
        x: 8,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'USER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-hr-sig',
        name: 'hr_signature',
        label: 'HR / Manager Verification',
        type: 'signature',
        pageNumber: 1,
        x: 54,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'APPROVER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-qr',
        name: 'qr_verification',
        label: 'Security QR Code',
        type: 'qr_code',
        pageNumber: 1,
        x: 8,
        y: 84,
        width: 12,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-stamp',
        name: 'company_stamp',
        label: 'Company Authorized Stamp',
        type: 'company_stamp',
        pageNumber: 1,
        x: 74,
        y: 84,
        width: 18,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
    ];

    const bikeHandoverFields: FormField[] = [
      {
        id: 'fld-bhf-num',
        name: 'document_number',
        label: 'Document Number',
        type: 'document_number',
        pageNumber: 1,
        x: 64,
        y: 6.5,
        width: 30,
        height: 3.2,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-bhf-rider',
        name: 'rider_name',
        label: 'Rider Full Name',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'e.g. Tariq Mansoor',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-eid',
        name: 'emirates_id',
        label: 'Rider Emirates ID Number',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '784-1990-1234567-1',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-plate',
        name: 'plate_number',
        label: 'Bike Plate Number & Emirate',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'Dubai 89412',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-chassis',
        name: 'chassis_number',
        label: 'Chassis / Engine Number',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'MD2A12BY7N12093',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-odo',
        name: 'current_odometer',
        label: 'Current Odometer (KM)',
        type: 'number',
        pageNumber: 1,
        x: 8,
        y: 42,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '12450',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-box',
        name: 'delivery_box_issued',
        label: 'Delivery Hot/Cold Box & Rack Issued',
        type: 'checkbox',
        pageNumber: 1,
        x: 52,
        y: 42,
        width: 40,
        height: 3.5,
        required: false,
        defaultValue: 'true',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-helmet',
        name: 'safety_gear_issued',
        label: 'DOT Helmet, Reflective Vest, Rain Jacket Issued',
        type: 'checkbox',
        pageNumber: 1,
        x: 8,
        y: 49,
        width: 84,
        height: 3.5,
        required: false,
        defaultValue: 'true',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-notes',
        name: 'condition_notes',
        label: 'Mechanical & Body Condition Remarks',
        type: 'textarea',
        pageNumber: 1,
        x: 8,
        y: 56,
        width: 84,
        height: 7,
        fontSize: 9.5,
        required: true,
        defaultValue: 'Clean condition, tires good, fresh oil change, no scratches on fairing.',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-r-sig',
        name: 'rider_signature',
        label: 'Rider Custody Acceptance Signature',
        type: 'signature',
        pageNumber: 1,
        x: 8,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'USER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-m-sig',
        name: 'fleet_officer_signature',
        label: 'Fleet Officer Handover Signature',
        type: 'signature',
        pageNumber: 1,
        x: 54,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'APPROVER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-bhf-qr',
        name: 'qr_verification',
        label: 'Security QR Code',
        type: 'qr_code',
        pageNumber: 1,
        x: 8,
        y: 84,
        width: 12,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-bhf-stamp',
        name: 'company_stamp',
        label: 'Company Authorized Stamp',
        type: 'company_stamp',
        pageNumber: 1,
        x: 74,
        y: 84,
        width: 18,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
    ];

    const salaryAdvanceFields: FormField[] = [
      {
        id: 'fld-saf-num',
        name: 'document_number',
        label: 'Document Number',
        type: 'document_number',
        pageNumber: 1,
        x: 64,
        y: 6.5,
        width: 30,
        height: 3.2,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-saf-emp',
        name: 'employee_name',
        label: 'Employee Full Name',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'Employee Name',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-id',
        name: 'employee_id',
        label: 'Employee / Staff ID',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'EMP-000',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-amt',
        name: 'advance_amount_aed',
        label: 'Requested Advance Amount (AED)',
        type: 'number',
        pageNumber: 1,
        x: 8,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '2000',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-ded',
        name: 'deduction_period_months',
        label: 'Installment Deduction Period',
        type: 'dropdown',
        pageNumber: 1,
        x: 52,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        options: ['1 Month (Next Payroll)', '2 Months Equal Split', '3 Months Equal Split'],
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-reason',
        name: 'advance_reason',
        label: 'Emergency / Purpose of Advance',
        type: 'textarea',
        pageNumber: 1,
        x: 8,
        y: 43,
        width: 84,
        height: 8,
        fontSize: 9.5,
        required: true,
        placeholder: 'Medical emergency, family visit, or home expense reason.',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-sig1',
        name: 'employee_signature',
        label: 'Employee Undertaking Signature',
        type: 'signature',
        pageNumber: 1,
        x: 8,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'USER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-sig2',
        name: 'finance_head_signature',
        label: 'Finance Director Sanction Signature',
        type: 'signature',
        pageNumber: 1,
        x: 54,
        y: 73,
        width: 38,
        height: 8,
        required: true,
        signerRole: 'APPROVER',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-saf-qr',
        name: 'qr_verification',
        label: 'Security QR Code',
        type: 'qr_code',
        pageNumber: 1,
        x: 8,
        y: 84,
        width: 12,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-saf-stamp',
        name: 'company_stamp',
        label: 'Company Authorized Stamp',
        type: 'company_stamp',
        pageNumber: 1,
        x: 74,
        y: 84,
        width: 18,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
    ];

    const salaryCertificateFields: FormField[] = [
      {
        id: 'fld-ssc-num',
        name: 'document_number',
        label: 'Official Certificate Number',
        type: 'document_number',
        pageNumber: 1,
        x: 64,
        y: 6.5,
        width: 30,
        height: 3.2,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-ssc-emp-name',
        name: 'employee_name',
        label: 'Staff Full Name',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'e.g. Tariq Mansoor',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-emp-id',
        name: 'employee_id',
        label: 'Staff / Badge ID',
        type: 'text',
        pageNumber: 1,
        x: 52,
        y: 28,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'GW-088',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-desig',
        name: 'designation',
        label: 'Designation / Job Title',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'Fleet & Dispatch Supervisor',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-join',
        name: 'joining_date',
        label: 'Date of Joining',
        type: 'date',
        pageNumber: 1,
        x: 52,
        y: 35,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-basic',
        name: 'basic_salary',
        label: 'Basic Salary (AED)',
        type: 'number',
        pageNumber: 1,
        x: 8,
        y: 42,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '5500',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-allow',
        name: 'allowances',
        label: 'Allowances (Housing & Transport) (AED)',
        type: 'number',
        pageNumber: 1,
        x: 52,
        y: 42,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '2500',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-gross',
        name: 'gross_monthly_salary',
        label: 'Total Gross Monthly Salary (AED)',
        type: 'number',
        pageNumber: 1,
        x: 8,
        y: 49,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: '8000',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-purpose',
        name: 'certificate_purpose',
        label: 'Purpose of Certificate',
        type: 'dropdown',
        pageNumber: 1,
        x: 52,
        y: 49,
        width: 40,
        height: 3.5,
        fontSize: 10,
        required: true,
        options: [
          'Bank Account Opening / Salary Transfer',
          'Personal Loan / Auto Finance Application',
          'Embassy Visa Application',
          'Family Residence Visa Sponsorship',
          'General Verification',
        ],
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-recipient',
        name: 'addressed_to',
        label: 'Addressed To / Recipient',
        type: 'text',
        pageNumber: 1,
        x: 8,
        y: 56,
        width: 84,
        height: 3.5,
        fontSize: 10,
        required: true,
        placeholder: 'To Whom It May Concern (or Bank Name)',
        defaultValue: 'To Whom It May Concern',
        visibility: true,
        editable: true,
      },
      {
        id: 'fld-ssc-qr',
        name: 'qr_verification',
        label: 'Tamper-evident QR Code',
        type: 'qr_code',
        pageNumber: 1,
        x: 8,
        y: 83,
        width: 13,
        height: 10,
        required: true,
        visibility: true,
        editable: false,
      },
      {
        id: 'fld-ssc-hr-sig',
        name: 'hr_signature',
        label: 'Authorized HR Signatory',
        type: 'signature',
        pageNumber: 1,
        x: 35,
        y: 84,
        width: 34,
        height: 8,
        required: true,
        visibility: true,
        editable: false,
        signerRole: 'APPROVER',
      },
      {
        id: 'fld-ssc-stamp',
        name: 'company_stamp',
        label: 'Corporate Seal & Stamp',
        type: 'company_stamp',
        pageNumber: 1,
        x: 74,
        y: 84,
        width: 18,
        height: 9,
        required: true,
        visibility: true,
        editable: false,
      },
    ];

    this.formTemplates = [
      {
        id: 'form-leave',
        formName: 'Employee Leave Application',
        formCode: 'LF',
        description: 'Official corporate leave request and manager verification form with atomic tracking',
        companyScope: 'ALL',
        companyIds: [],
        departmentId: 'dept-hr',
        category: 'HR Forms',
        currentVersion: 1,
        effectiveDate: '2026-01-01',
        status: 'ACTIVE',
        instructions:
          'Submit at least 10 calendar days prior to planned leave commencement. Must be approved by Department Head and HR.',
        pdfTemplateUrl: '',
        pdfPageCount: 1,
        fields: leaveFields,
        numberingRuleId: 'rule-leave',
        versions: [
          {
            version: 1,
            fields: leaveFields,
            pdfTemplateUrl: '',
            pdfPageCount: 1,
            updatedAt: '2026-01-01T00:00:00.000Z',
            updatedBy: 'Mohammed Al-Qasimi',
            changelog: 'Initial published corporate version',
          },
        ],
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        createdBy: 'Mohammed Al-Qasimi',
      },
      {
        id: 'form-bike-handover',
        formName: 'Fleet Bike & Asset Handover Form',
        formCode: 'BHF',
        description: 'Commercial motorbike, delivery equipment, and fuel card handover custody document',
        companyScope: 'ALL',
        companyIds: [],
        departmentId: 'dept-ops',
        category: 'Operations Forms',
        currentVersion: 1,
        effectiveDate: '2026-01-01',
        status: 'ACTIVE',
        instructions:
          'Inspect bike condition thoroughly before signing. Record mileage, scratches and attached delivery hardware.',
        pdfTemplateUrl: '',
        pdfPageCount: 1,
        fields: bikeHandoverFields,
        numberingRuleId: 'rule-bike-handover',
        versions: [
          {
            version: 1,
            fields: bikeHandoverFields,
            pdfTemplateUrl: '',
            pdfPageCount: 1,
            updatedAt: '2026-01-01T00:00:00.000Z',
            updatedBy: 'Mohammed Al-Qasimi',
            changelog: 'Initial operations release',
          },
        ],
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        createdBy: 'Mohammed Al-Qasimi',
      },
      {
        id: 'form-salary-advance',
        formName: 'Staff Salary Advance Request',
        formCode: 'SAF',
        description: 'Payroll advance request and repayment undertaking voucher',
        companyScope: 'ALL',
        companyIds: [],
        departmentId: 'dept-fin',
        category: 'Finance Forms',
        currentVersion: 1,
        effectiveDate: '2026-01-01',
        status: 'ACTIVE',
        instructions:
          'Maximum advance limit is 50% of monthly basic wage. Deductions apply automatically on succeeding WPS cycle.',
        pdfTemplateUrl: '',
        pdfPageCount: 1,
        fields: salaryAdvanceFields,
        numberingRuleId: 'rule-salary-advance',
        versions: [
          {
            version: 1,
            fields: salaryAdvanceFields,
            pdfTemplateUrl: '',
            pdfPageCount: 1,
            updatedAt: '2026-01-01T00:00:00.000Z',
            updatedBy: 'Mohammed Al-Qasimi',
            changelog: 'Initial finance version',
          },
        ],
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        createdBy: 'Mohammed Al-Qasimi',
      },
      {
        id: 'form-salary-certificate',
        formName: 'Staff Salary & Employment Certificate',
        formCode: 'SSC',
        description: 'Official corporate salary certificate for bank accounts, loans, visa applications, and embassy submissions',
        companyScope: 'ALL',
        companyIds: [],
        departmentId: 'dept-hr',
        category: 'HR Forms',
        currentVersion: 1,
        effectiveDate: '2026-01-01',
        status: 'ACTIVE',
        instructions:
          'Fill in employee salary and recipient information accurately. Digital signature by HR and company seal are verified via QR code.',
        pdfTemplateUrl: '',
        pdfPageCount: 1,
        fields: salaryCertificateFields,
        numberingRuleId: 'rule-salary-cert',
        versions: [
          {
            version: 1,
            fields: salaryCertificateFields,
            pdfTemplateUrl: '',
            pdfPageCount: 1,
            updatedAt: '2026-01-01T00:00:00.000Z',
            updatedBy: 'Mohammed Al-Qasimi',
            changelog: 'Initial published corporate salary certificate template',
          },
        ],
        createdAt: '2026-01-01T00:00:00.000Z',
        updatedAt: '2026-01-01T00:00:00.000Z',
        createdBy: 'Mohammed Al-Qasimi',
      },
    ];

    // 7. Seeded Documents across different lifecycle stages
    this.documents = [
      {
        id: 'doc-seed-001',
        documentNumber: 'GWDS-HR-LF-2026-001024',
        secureVerificationToken: 'c8712f5a043e9b1d6240ae754d921b3a',
        formTemplateId: 'form-leave',
        formTemplateVersion: 1,
        formName: 'Employee Leave Application',
        formCode: 'LF',
        companyId: 'comp-gwds',
        companyName: 'Gulf Way Delivery Services LLC',
        departmentId: 'dept-ops',
        employeeName: 'Mohammed Irfan',
        employeeId: 'RDR-1092',
        status: 'FINAL',
        signingMethod: 'PHYSICAL',
        values: {
          employee_name: 'Mohammed Irfan',
          employee_id: 'RDR-1092',
          department: 'Operations',
          designation: 'Senior Fleet Dispatcher',
          leave_type: 'Annual Leave',
          total_days: '30',
          start_date: '2026-10-01',
          end_date: '2026-10-31',
          contact_number: '+971 54 332 9988',
          leave_reason: 'Annual vacation to visit family and hometown.',
        },
        finalPdfHashSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        statusHistory: [
          {
            id: 'sh-1',
            previousStatus: 'DRAFT',
            newStatus: 'NUMBER_ASSIGNED',
            changedBy: 'usr-rider-irfan',
            changedByName: 'Mohammed Irfan',
            changedAt: '2026-09-06T09:15:00.000Z',
            remarks: 'Official document number allocated: GWDS-HR-LF-2026-001024',
          },
          {
            id: 'sh-2',
            previousStatus: 'NUMBER_ASSIGNED',
            newStatus: 'AWAITING_SIGNATURE',
            changedBy: 'usr-rider-irfan',
            changedByName: 'Mohammed Irfan',
            changedAt: '2026-09-06T09:16:00.000Z',
            remarks: 'PDF downloaded for physical sign & thumbprint',
          },
          {
            id: 'sh-3',
            previousStatus: 'AWAITING_SIGNATURE',
            newStatus: 'SIGNED',
            changedBy: 'usr-rider-irfan',
            changedByName: 'Mohammed Irfan',
            changedAt: '2026-09-06T11:45:00.000Z',
            remarks: 'Scanned physical signed copy uploaded',
          },
          {
            id: 'sh-4',
            previousStatus: 'SIGNED',
            newStatus: 'APPROVED',
            changedBy: 'usr-hr-fatima',
            changedByName: 'Fatima Al-Zahra',
            changedAt: '2026-09-06T14:20:00.000Z',
            remarks: 'HR leave verification complete. Eligible balance verified.',
          },
          {
            id: 'sh-5',
            previousStatus: 'APPROVED',
            newStatus: 'FINAL',
            changedBy: 'usr-admin',
            changedByName: 'Mohammed Al-Qasimi',
            changedAt: '2026-09-06T15:00:00.000Z',
            remarks: 'Document locked as immutable final record with SHA-256 seal',
          },
        ],
        signatures: [],
        approvalHistory: [
          {
            id: 'app-1',
            stepName: 'HR Management Sanction',
            approverId: 'usr-hr-fatima',
            approverName: 'Fatima Al-Zahra',
            action: 'APPROVED',
            remarks: 'Approved with full leave entitlement balance.',
            actionAt: '2026-09-06T14:20:00.000Z',
          },
        ],
        createdAt: '2026-09-06T09:15:00.000Z',
        generatedPdfUrl: '/api/documents/doc-seed-001/pdf',
        createdBy: 'usr-rider-irfan',
        createdByName: 'Mohammed Irfan',
        updatedAt: '2026-09-06T15:00:00.000Z',
        finalizedAt: '2026-09-06T15:00:00.000Z',
      },
      {
        id: 'doc-seed-002',
        documentNumber: 'GWDS-OPS-BHF-2026-001055',
        secureVerificationToken: 'd91a45e7f12c8b3e44501a98c7602e11',
        formTemplateId: 'form-bike-handover',
        formTemplateVersion: 1,
        formName: 'Fleet Bike & Asset Handover Form',
        formCode: 'BHF',
        companyId: 'comp-gwds',
        companyName: 'Gulf Way Delivery Services LLC',
        departmentId: 'dept-ops',
        employeeName: 'Ahmed Bilal',
        employeeId: 'RDR-2041',
        status: 'AWAITING_SIGNATURE',
        signingMethod: 'PHYSICAL',
        values: {
          rider_name: 'Ahmed Bilal',
          emirates_id: '784-1994-3918274-2',
          plate_number: 'Dubai 44912',
          chassis_number: 'ME4JF5412LK88921',
          current_odometer: '8340',
          delivery_box_issued: true,
          safety_gear_issued: true,
          condition_notes: 'Flawless condition, front brake pads renewed, box insulated.',
        },
        statusHistory: [
          {
            id: 'sh-b1',
            previousStatus: 'DRAFT',
            newStatus: 'NUMBER_ASSIGNED',
            changedBy: 'usr-ops-tariq',
            changedByName: 'Tariq Mansoor',
            changedAt: '2026-09-07T10:00:00.000Z',
            remarks: 'Official document number allocated: GWDS-OPS-BHF-2026-001055',
          },
          {
            id: 'sh-b2',
            previousStatus: 'NUMBER_ASSIGNED',
            newStatus: 'AWAITING_SIGNATURE',
            changedBy: 'usr-ops-tariq',
            changedByName: 'Tariq Mansoor',
            changedAt: '2026-09-07T10:05:00.000Z',
            remarks: 'Ready for rider physical signature & vehicle handover check',
          },
        ],
        generatedPdfUrl: '/api/documents/doc-seed-002/pdf',
        signatures: [],
        approvalHistory: [],
        createdAt: '2026-09-07T10:00:00.000Z',
        createdBy: 'usr-ops-tariq',
        createdByName: 'Tariq Mansoor',
        updatedAt: '2026-09-07T10:05:00.000Z',
      },
      {
        id: 'doc-seed-003',
        documentNumber: 'GWDS-HR-LF-2026-001025',
        secureVerificationToken: 'vt_seed_leave_001025_signed',
        formTemplateId: 'form-leave',
        formCode: 'LF',
        formName: 'Annual & Emergency Leave Application Form',
        formTemplateVersion: 1,
        companyId: 'comp-gwds',
        companyName: 'Gulf Way Delivery Services LLC',
        departmentId: 'dept-hr',
        employeeName: 'Mohammed Irfan',
        employeeId: 'EMP-9022',
        status: 'AWAITING_APPROVAL',
        signingMethod: 'DIGITAL',
        values: {
          employee_name: 'Mohammed Irfan',
          employee_id: 'EMP-9022',
          department: 'Operations & Fleet Logistics',
          leave_type: 'Annual Leave',
          start_date: '2026-09-15',
          end_date: '2026-09-30',
          total_days: '15',
          emergency_contact: '+971 52 987 6543',
          handover_to: 'Ahmed Bilal (RDR-2041)',
          reason: 'Scheduled annual vacation to home country with family.',
        },
        generatedPdfUrl: '/api/documents/doc-seed-003/pdf',
        statusHistory: [
          {
            id: 'sh-c1',
            previousStatus: 'DRAFT',
            newStatus: 'NUMBER_ASSIGNED',
            changedBy: 'usr-admin',
            changedByName: 'Mohammed Al-Qasimi',
            changedAt: '2026-09-08T08:00:00.000Z',
            remarks: 'Official document number allocated: GWDS-HR-LF-2026-001025',
          },
          {
            id: 'sh-c2',
            previousStatus: 'NUMBER_ASSIGNED',
            newStatus: 'AWAITING_SIGNATURE',
            changedBy: 'usr-rider-irfan',
            changedByName: 'Mohammed Irfan',
            changedAt: '2026-09-08T08:15:00.000Z',
            remarks: 'Ready for digital applicant signature',
          },
          {
            id: 'sh-c3',
            previousStatus: 'AWAITING_SIGNATURE',
            newStatus: 'AWAITING_APPROVAL',
            changedBy: 'usr-rider-irfan',
            changedByName: 'Mohammed Irfan',
            changedAt: '2026-09-08T08:30:00.000Z',
            remarks: 'Digitally signed by employee Mohammed Irfan. Submitted to HR Manager for formal approval.',
          },
        ],
        signatures: [
          {
            id: 'sig-seed-003',
            fieldId: 'signature',
            signerName: 'Mohammed Irfan',
            signerRole: 'Standard Employee / Rider',
            signatureDataUrl: 'data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="200" height="60"><path d="M10 40 Q 50 10 90 40 T 170 30" stroke="%231e3a8a" stroke-width="2.5" fill="none"/></svg>',
            type: 'DRAWN',
            signedAt: '2026-09-08T08:30:00.000Z',
            userId: 'usr-rider-irfan',
            ipAddress: '192.168.1.45',
          },
        ],
        approvalHistory: [],
        createdAt: '2026-09-08T08:00:00.000Z',
        createdBy: 'usr-admin',
        createdByName: 'Mohammed Al-Qasimi',
        updatedAt: '2026-09-08T08:30:00.000Z',
      },
    ];

    // 8. Seed Audit Logs
    this.auditLogs = [
      {
        id: 'aud-1',
        userId: 'usr-admin',
        userName: 'Mohammed Al-Qasimi',
        action: 'Form Published',
        resourceType: 'FORM',
        resourceId: 'form-leave',
        newValue: 'Version 1 Published',
        remarks: 'Published Leave Application with atomic numbering rule',
        timestamp: '2026-01-01T00:00:00.000Z',
        ipAddress: '194.170.12.8',
        companyId: 'comp-gwds',
      },
      {
        id: 'aud-2',
        userId: 'usr-rider-irfan',
        userName: 'Mohammed Irfan',
        action: 'Document Number Generated',
        resourceType: 'DOCUMENT',
        resourceId: 'doc-seed-001',
        newValue: 'GWDS-HR-LF-2026-001024',
        remarks: 'Sequence counter incremented to 1024',
        timestamp: '2026-09-06T09:15:00.000Z',
        ipAddress: '83.110.201.55',
        companyId: 'comp-gwds',
      },
      {
        id: 'aud-3',
        userId: 'usr-admin',
        userName: 'Mohammed Al-Qasimi',
        action: 'Final Document Sealed',
        resourceType: 'DOCUMENT',
        resourceId: 'doc-seed-001',
        newValue: 'SHA256: 9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
        remarks: 'Document marked FINAL and locked from edits',
        timestamp: '2026-09-06T15:00:00.000Z',
        ipAddress: '194.170.12.8',
        companyId: 'comp-gwds',
      },
    ];
  }

  // Helper methods
  public recordAudit(
    userId: string,
    userName: string,
    action: string,
    resourceType: AuditLog['resourceType'],
    resourceId: string,
    options: {
      oldValue?: string;
      newValue?: string;
      remarks?: string;
      ipAddress?: string;
      userAgent?: string;
      companyId?: string;
    } = {}
  ): AuditLog {
    const log: AuditLog = {
      id: `aud-${Date.now()}-${Math.random().toString(36).substring(2, 7)}`,
      userId,
      userName,
      action,
      resourceType,
      resourceId,
      oldValue: options.oldValue,
      newValue: options.newValue,
      remarks: options.remarks,
      timestamp: new Date().toISOString(),
      ipAddress: options.ipAddress || '127.0.0.1',
      userAgent: options.userAgent || 'Web/Browser',
      companyId: options.companyId,
    };
    this.auditLogs.unshift(log);
    return log;
  }

  public deleteCompany(id: string): boolean {
    const idx = this.companies.findIndex((c) => c.id === id);
    if (idx === -1) return false;
    const removed = this.companies.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Company Deleted', 'COMPANY', id, {
      remarks: `Deleted company: ${removed.name} (${removed.code})`,
    });
    return true;
  }

  public deleteUser(id: string): boolean {
    const idx = this.users.findIndex((u) => u.id === id);
    if (idx === -1) return false;
    const removed = this.users.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'User Deleted', 'USER', id, {
      remarks: `Deleted user: ${removed.fullName} (${removed.roleName}, ${removed.email})`,
    });
    return true;
  }

  public createRole(roleData: Partial<Role>): Role {
    const newRole: Role = {
      id: `role-${Date.now()}`,
      code: (roleData.code || `ROLE_${Date.now()}`).toUpperCase(),
      name: roleData.name || 'Custom Role',
      description: roleData.description || 'Custom defined role with selected permissions',
      isSystem: false,
      permissions: roleData.permissions || ['DOCUMENT_VIEW', 'DOCUMENT_DOWNLOAD'],
    };
    this.roles.push(newRole);
    this.recordAudit('usr-admin', 'Super Administrator', 'Role Created', 'AUTH', newRole.id, {
      remarks: `Created role: ${newRole.name} with ${newRole.permissions.length} capabilities`,
    });
    return newRole;
  }

  public updateRole(id: string, updates: Partial<Role>): Role | null {
    const idx = this.roles.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    const existing = this.roles[idx];
    const updated: Role = {
      ...existing,
      ...updates,
      id: existing.id,
      isSystem: existing.isSystem, // preserve system flag
    };
    this.roles[idx] = updated;

    // Update users who have this role assigned
    this.users.forEach((u) => {
      if (u.roleId === id) {
        if (updates.name) u.roleName = updates.name;
        if (updates.permissions) u.permissions = updates.permissions;
      }
    });

    this.recordAudit('usr-admin', 'Super Administrator', 'Role Updated', 'AUTH', id, {
      remarks: `Updated role: ${updated.name}`,
    });
    return updated;
  }

  public deleteRole(id: string): boolean {
    const idx = this.roles.findIndex((r) => r.id === id);
    if (idx === -1) return false;
    const removed = this.roles.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Role Deleted', 'AUTH', id, {
      remarks: `Deleted role: ${removed.name} (${removed.code})`,
    });
    return true;
  }

  public updateNumberingRule(id: string, updates: Partial<NumberingRule>): NumberingRule | null {
    const idx = this.numberingRules.findIndex((r) => r.id === id);
    if (idx === -1) return null;
    const existing = this.numberingRules[idx];
    const updated: NumberingRule = {
      ...existing,
      ...updates,
      id: existing.id,
      updatedAt: new Date().toISOString(),
    };
    this.numberingRules[idx] = updated;
    this.recordAudit('usr-admin', 'Super Administrator', 'Numbering Rule Updated', 'NUMBERING', id, {
      newValue: `${updated.name}: ${updated.pattern}`,
    });
    return updated;
  }

  public deleteNumberingRule(id: string): boolean {
    const idx = this.numberingRules.findIndex((r) => r.id === id);
    if (idx === -1) return false;
    const removed = this.numberingRules.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Numbering Rule Deleted', 'NUMBERING', id, {
      remarks: `Deleted numbering rule: ${removed.name} (${removed.pattern})`,
    });
    return true;
  }

  public deleteForm(id: string): boolean {
    const idx = this.formTemplates.findIndex((f) => f.id === id);
    if (idx === -1) return false;
    const removed = this.formTemplates.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Form Deleted', 'FORM', id, {
      remarks: `Deleted form: ${removed.formName} (${removed.formCode})`,
    });
    return true;
  }

  public deleteDocument(id: string): boolean {
    const idx = this.documents.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    const removed = this.documents.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Document Deleted', 'DOCUMENT', id, {
      remarks: `Deleted document ${removed.documentNumber || removed.id} (${removed.formName})`,
    });
    return true;
  }

  public createDepartment(deptData: Partial<Department>): Department {
    const newDept: Department = {
      id: `dept-${Date.now()}`,
      code: (deptData.code || 'DEPT').toUpperCase(),
      name: deptData.name || 'New Department',
    };
    this.departments.push(newDept);
    this.recordAudit('usr-admin', 'Super Administrator', 'Department Created', 'COMPANY', newDept.id, {
      newValue: `${newDept.name} (${newDept.code})`,
    });
    return newDept;
  }

  public deleteDepartment(id: string): boolean {
    const idx = this.departments.findIndex((d) => d.id === id);
    if (idx === -1) return false;
    const removed = this.departments.splice(idx, 1)[0];
    this.recordAudit('usr-admin', 'Super Administrator', 'Department Deleted', 'COMPANY', id, {
      remarks: `Deleted department ${removed.name} (${removed.code})`,
    });
    return true;
  }

  public clearSampleData(): void {
    this.companies = [];
    this.documents = [];
    this.auditLogs = [];
    this.recordAudit('usr-admin', 'Super Administrator', 'Database Cleared', 'AUTH', 'system', {
      remarks: 'All sample companies and documents cleared. Clean empty database ready for manual entry.',
    });
  }
}

export const store = new InMemoryStore();
