import React, { useState } from 'react';
import {
  FileText,
  Upload,
  Plus,
  Trash2,
  Eye,
  Check,
  Move,
  Layers,
  Sparkles,
  Play,
  Save,
  Shield,
  FileCheck,
  HelpCircle,
  Binary,
} from 'lucide-react';
import {
  FormField,
  FormTemplate,
  FieldType,
  Company,
  Department,
  NumberingRule,
} from '../types/index.js';
import { api } from '../api.js';

interface FormBuilderProps {
  companies: Company[];
  departments: Department[];
  numberingRules: NumberingRule[];
  existingForm?: FormTemplate | null;
  onSaveSuccess: (form: FormTemplate) => void;
  onCancel: () => void;
}

const FIELD_TOOLBAR_ITEMS: Array<{ type: FieldType; label: string; icon: string }> = [
  { type: 'text', label: 'Text Field', icon: 'Aa' },
  { type: 'number', label: 'Number', icon: '123' },
  { type: 'date', label: 'Date', icon: '📅' },
  { type: 'time', label: 'Time', icon: '⏰' },
  { type: 'dropdown', label: 'Dropdown', icon: '▼' },
  { type: 'radio', label: 'Radio Button', icon: '◉' },
  { type: 'checkbox', label: 'Checkbox', icon: '☑' },
  { type: 'textarea', label: 'Textarea', icon: '¶' },
  { type: 'employee_search', label: 'Employee Search', icon: '👤' },
  { type: 'company_search', label: 'Company Search', icon: '🏢' },
  { type: 'signature', label: 'Signature', icon: '✍️' },
  { type: 'thumbprint', label: 'Thumbprint', icon: '🖐️' },
  { type: 'company_stamp', label: 'Company Stamp', icon: '🛡️' },
  { type: 'photo', label: 'Photo', icon: '🖼️' },
  { type: 'attachment', label: 'Attachment', icon: '📎' },
  { type: 'document_number', label: 'Document Number', icon: '№' },
  { type: 'generated_date', label: 'Generated Date', icon: '🗓️' },
  { type: 'generated_by', label: 'Generated By', icon: '✍' },
  { type: 'qr_code', label: 'QR Code', icon: '▣' },
  { type: 'barcode', label: 'Barcode', icon: '|||' },
];

export const FormBuilder: React.FC<FormBuilderProps> = ({
  companies,
  departments,
  numberingRules,
  existingForm,
  onSaveSuccess,
  onCancel,
}) => {
  // General Info
  const [formName, setFormName] = useState(existingForm?.formName || '');
  const [formCode, setFormCode] = useState(existingForm?.formCode || '');
  const [description, setDescription] = useState(existingForm?.description || '');
  const [departmentId, setDepartmentId] = useState(existingForm?.departmentId || 'dept-hr');
  const [category, setCategory] = useState(existingForm?.category || 'HR Forms');
  const [companyScope, setCompanyScope] = useState<'ALL' | 'SPECIFIC'>(
    existingForm?.companyScope || 'ALL'
  );
  const [selectedCompanyIds, setSelectedCompanyIds] = useState<string[]>(
    existingForm?.companyIds || []
  );
  const [numberingRuleId, setNumberingRuleId] = useState(
    existingForm?.numberingRuleId || numberingRules[0]?.id || 'rule-default'
  );
  const [instructions, setInstructions] = useState(
    existingForm?.instructions || 'Review all mandatory fields carefully before requesting official numbering.'
  );

  // Mapped Fields
  const [fields, setFields] = useState<FormField[]>(existingForm?.fields || []);
  const [selectedFieldId, setSelectedFieldId] = useState<string | null>(null);

  // PDF Template State
  const [pdfTemplateUrl, setPdfTemplateUrl] = useState(existingForm?.pdfTemplateUrl || '');
  const [pdfFileName, setPdfFileName] = useState(existingForm?.pdfTemplateUrl ? 'Existing Template' : '');

  // Active Tab / View Mode
  const [activeStep, setActiveStep] = useState<'SETTINGS' | 'MAPPER' | 'TEST'>('SETTINGS');
  const [isPublishing, setIsPublishing] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [testFillValues, setTestFillValues] = useState<Record<string, any>>({});
  const [previewPdfBase64, setPreviewPdfBase64] = useState<string | null>(null);
  const [isLoadingPreview, setIsLoadingPreview] = useState(false);

  // Selected Field for Inspector
  const selectedField = fields.find((f) => f.id === selectedFieldId);

  // Handle PDF upload
  const handlePdfUpload = (e: React.ChangeEvent<HTMLInputElement>) => {
    const file = e.target.files?.[0];
    if (!file) return;

    if (file.type !== 'application/pdf') {
      setErrorMsg('Please upload a valid PDF document.');
      return;
    }

    setPdfFileName(file.name);
    const reader = new FileReader();
    reader.onload = () => {
      setPdfTemplateUrl(reader.result as string);
      setErrorMsg('');
    };
    reader.readAsDataURL(file);
  };

  // Add field to visual canvas
  const handleAddField = (type: FieldType) => {
    const newFieldId = `fld-${Date.now()}`;
    const defaultLabel = FIELD_TOOLBAR_ITEMS.find((item) => item.type === type)?.label || 'Field';
    const fieldNameKey = `${type}_${fields.length + 1}`;

    const newField: FormField = {
      id: newFieldId,
      name: type === 'document_number' ? 'document_number' : type === 'qr_code' ? 'qr_verification' : fieldNameKey,
      label: defaultLabel,
      type,
      pageNumber: 1,
      x: 10 + (fields.length % 5) * 5,
      y: 20 + (fields.length % 8) * 6,
      width: type === 'signature' ? 38 : type === 'qr_code' ? 14 : type === 'company_stamp' ? 18 : 35,
      height: type === 'signature' ? 8 : type === 'qr_code' ? 10 : type === 'company_stamp' ? 10 : 3.5,
      fontSize: 10,
      fontFamily: 'Helvetica',
      fontStyle: 'normal',
      alignment: 'left',
      required: type === 'document_number' || type === 'signature' || type === 'qr_code' ? true : false,
      visibility: true,
      editable: type !== 'document_number' && type !== 'qr_code' && type !== 'company_stamp',
      signerRole: type === 'signature' ? 'USER' : undefined,
    };

    setFields([...fields, newField]);
    setSelectedFieldId(newFieldId);
  };

  const updateSelectedField = (updates: Partial<FormField>) => {
    if (!selectedFieldId) return;
    setFields(fields.map((f) => (f.id === selectedFieldId ? { ...f, ...updates } : f)));
  };

  const removeSelectedField = (id: string) => {
    setFields(fields.filter((f) => f.id !== id));
    if (selectedFieldId === id) setSelectedFieldId(null);
  };

  // Run Test Fill live preview
  const handleRunTestPreview = async () => {
    setIsLoadingPreview(true);
    setErrorMsg('');
    try {
      const dummyTemplate: FormTemplate = {
        id: existingForm?.id || 'temp-test',
        formName: formName || 'Untitled Form',
        formCode: formCode || 'UF',
        description,
        companyScope,
        companyIds: selectedCompanyIds,
        departmentId,
        category,
        currentVersion: existingForm?.currentVersion || 1,
        effectiveDate: new Date().toISOString().split('T')[0],
        status: 'DRAFT',
        instructions,
        pdfTemplateUrl,
        pdfPageCount: 1,
        fields,
        numberingRuleId,
        versions: [],
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
        createdBy: 'Admin',
      };

      const res = await api.testPreviewPdf(dummyTemplate, testFillValues);
      setPreviewPdfBase64(res.pdfBase64);
    } catch (err: any) {
      setErrorMsg(`Failed to generate test preview: ${err.message}`);
    } finally {
      setIsLoadingPreview(false);
    }
  };

  // Save / Publish
  const handleSaveForm = async (publishImmediately: boolean) => {
    if (!formName.trim()) {
      setErrorMsg('Form Name is required.');
      return;
    }
    if (!formCode.trim()) {
      setErrorMsg('Form Code is required (e.g. LF, SAF, BHF).');
      return;
    }

    setIsPublishing(true);
    setErrorMsg('');

    try {
      let savedForm: FormTemplate;

      if (existingForm) {
        // Strict versioning rule: if modifying published form, update creates a new version
        savedForm = await api.updateForm(existingForm.id, {
          formName,
          formCode: formCode.toUpperCase(),
          description,
          departmentId,
          category,
          companyScope,
          companyIds: selectedCompanyIds,
          instructions,
          pdfTemplateUrl,
          fields,
          numberingRuleId,
          changelog: `Form updated. Fields count: ${fields.length}`,
        });
      } else {
        savedForm = await api.createForm({
          formName,
          formCode: formCode.toUpperCase(),
          description,
          departmentId,
          category,
          companyScope,
          companyIds: selectedCompanyIds,
          instructions,
          pdfTemplateUrl,
          pdfPageCount: 1,
          fields,
          numberingRuleId,
        });
      }

      if (publishImmediately) {
        const pubResult = await api.publishForm(savedForm.id);
        savedForm = pubResult.form;
      }

      onSaveSuccess(savedForm);
    } catch (err: any) {
      setErrorMsg(`Save failed: ${err.message}`);
    } finally {
      setIsPublishing(false);
    }
  };

  return (
    <div className="p-8 max-w-7xl mx-auto space-y-6">
      {/* Top Header */}
      <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 pb-4 border-b border-slate-200">
        <div>
          <div className="flex items-center gap-2">
            <span className="text-xs font-bold px-2 py-0.5 rounded-sm bg-blue-100 text-blue-700">
              FORM BUILDER ENGINE
            </span>
            {existingForm && (
              <span className="text-xs font-semibold px-2 py-0.5 rounded-sm bg-slate-100 text-slate-700">
                Version {existingForm.currentVersion} • {existingForm.status}
              </span>
            )}
          </div>
          <h2 className="text-xl font-bold text-slate-900 mt-1">
            {existingForm ? `Edit Form: ${existingForm.formName}` : 'Create New Company Form Template'}
          </h2>
          <p className="text-xs text-slate-500">
            Upload blank PDF templates, visually map coordinates for fields, bind numbering tokens, and test before publishing.
          </p>
        </div>

        <div className="flex items-center gap-3">
          <button
            onClick={onCancel}
            className="px-3.5 py-2 text-xs font-semibold text-slate-600 hover:text-slate-900 hover:bg-slate-100 rounded-lg transition-colors"
          >
            Cancel
          </button>
          <button
            onClick={() => handleSaveForm(false)}
            disabled={isPublishing}
            className="px-4 py-2 bg-slate-100 hover:bg-slate-200 text-slate-800 text-xs font-semibold rounded-lg transition-colors flex items-center gap-1.5"
          >
            <Save className="w-4 h-4" />
            <span>Save as Draft</span>
          </button>
          <button
            onClick={() => handleSaveForm(true)}
            disabled={isPublishing}
            className="px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white text-xs font-bold rounded-lg shadow-xs transition-colors flex items-center gap-1.5"
          >
            <Check className="w-4 h-4" />
            <span>Publish Template</span>
          </button>
        </div>
      </div>

      {errorMsg && (
        <div className="p-3.5 bg-rose-50 border border-rose-200 rounded-lg text-xs text-rose-700 font-medium flex items-center justify-between">
          <span>{errorMsg}</span>
          <button onClick={() => setErrorMsg('')} className="text-rose-500 font-bold hover:text-rose-800">
            ✕
          </button>
        </div>
      )}

      {/* Steps Navigation */}
      <div className="flex items-center border-b border-slate-200 space-x-6 text-xs font-semibold">
        <button
          onClick={() => setActiveStep('SETTINGS')}
          className={`pb-2.5 flex items-center gap-2 border-b-2 transition-colors ${
            activeStep === 'SETTINGS'
              ? 'border-blue-600 text-blue-600 font-bold'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <span>1. General Form Metadata</span>
        </button>
        <button
          onClick={() => setActiveStep('MAPPER')}
          className={`pb-2.5 flex items-center gap-2 border-b-2 transition-colors ${
            activeStep === 'MAPPER'
              ? 'border-blue-600 text-blue-600 font-bold'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <span>2. Visual PDF Field Mapping ({fields.length} Fields)</span>
        </button>
        <button
          onClick={() => {
            setActiveStep('TEST');
            handleRunTestPreview();
          }}
          className={`pb-2.5 flex items-center gap-2 border-b-2 transition-colors ${
            activeStep === 'TEST'
              ? 'border-blue-600 text-blue-600 font-bold'
              : 'border-transparent text-slate-500 hover:text-slate-800'
          }`}
        >
          <Play className="w-3.5 h-3.5 text-blue-600" />
          <span>3. Live Test-Fill & PDF Validation</span>
        </button>
      </div>

      {/* STEP 1: GENERAL SETTINGS */}
      {activeStep === 'SETTINGS' && (
        <div className="bg-white border border-slate-200 rounded-xl p-6 shadow-2xs space-y-6">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Form Title / Name <span className="text-rose-500">*</span>
              </label>
              <input
                type="text"
                value={formName}
                onChange={(e) => setFormName(e.target.value)}
                placeholder="e.g. Employee Leave Application"
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500 font-medium"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Form Code <span className="text-rose-500">*</span>
                <span className="text-[10px] text-slate-400 font-normal ml-1">
                  (Short prefix used in document numbering, e.g. LF, SAF, BHF)
                </span>
              </label>
              <input
                type="text"
                value={formCode}
                onChange={(e) => setFormCode(e.target.value.toUpperCase())}
                placeholder="LF"
                maxLength={8}
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500 font-mono font-bold"
              />
            </div>

            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Form Description
              </label>
              <textarea
                rows={2}
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="State the purpose, required attachments and organizational validity of this form..."
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500 font-medium"
              />
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Responsible Department
              </label>
              <select
                value={departmentId}
                onChange={(e) => setDepartmentId(e.target.value)}
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500"
              >
                {departments.map((d) => (
                  <option key={d.id} value={d.id}>
                    {d.code} - {d.name}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Category
              </label>
              <select
                value={category}
                onChange={(e) => setCategory(e.target.value)}
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500"
              >
                <option value="HR Forms">HR Forms</option>
                <option value="Finance Forms">Finance Forms</option>
                <option value="Operations Forms">Operations Forms</option>
                <option value="Fleet & Rider Forms">Fleet & Rider Forms</option>
                <option value="Legal & Compliance">Legal & Compliance</option>
                <option value="Administration">Administration</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Operating Company Scope
              </label>
              <select
                value={companyScope}
                onChange={(e) => setCompanyScope(e.target.value as any)}
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500"
              >
                <option value="ALL">Available to All Companies in Group</option>
                <option value="SPECIFIC">Restricted to Selected Companies</option>
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Document Numbering Rule Pattern
              </label>
              <select
                value={numberingRuleId}
                onChange={(e) => setNumberingRuleId(e.target.value)}
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500 font-mono text-[11px]"
              >
                {numberingRules.map((rule) => (
                  <option key={rule.id} value={rule.id}>
                    {rule.name} ({rule.pattern})
                  </option>
                ))}
              </select>
            </div>

            <div className="md:col-span-2">
              <label className="block text-xs font-bold text-slate-700 mb-1">
                Instructions for Submitting Employees
              </label>
              <input
                type="text"
                value={instructions}
                onChange={(e) => setInstructions(e.target.value)}
                placeholder="e.g. Submit at least 7 days before commencement. Physical signature requires company stamp."
                className="w-full text-xs px-3 py-2 border border-slate-300 rounded-lg focus:outline-hidden focus:border-blue-500"
              />
            </div>
          </div>

          {/* Blank PDF Template Upload Box */}
          <div className="pt-4 border-t border-slate-100">
            <h4 className="text-xs font-bold text-slate-800 mb-1 flex items-center gap-1.5">
              <Upload className="w-4 h-4 text-blue-600" />
              <span>Upload Blank PDF Template</span>
            </h4>
            <p className="text-xs text-slate-500 mb-3">
              Upload your company's existing blank form PDF. If left blank, Gulf Way DocFlow will automatically synthesize a standard corporate PDF layout.
            </p>

            <div className="flex items-center gap-4">
              <label className="px-4 py-2 bg-blue-50 hover:bg-blue-100 text-blue-700 border border-blue-200 rounded-lg text-xs font-semibold cursor-pointer transition-colors flex items-center gap-2">
                <FileText className="w-4 h-4" />
                <span>Select PDF File</span>
                <input
                  type="file"
                  accept="application/pdf"
                  onChange={handlePdfUpload}
                  className="hidden"
                />
              </label>

              {pdfFileName && (
                <span className="text-xs font-medium text-emerald-700 bg-emerald-50 px-2.5 py-1 rounded-md border border-emerald-200">
                  ✓ Template Loaded: {pdfFileName}
                </span>
              )}
            </div>
          </div>

          <div className="flex justify-end pt-4">
            <button
              onClick={() => setActiveStep('MAPPER')}
              className="px-5 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold shadow-xs transition-colors"
            >
              Continue to PDF Field Mapping →
            </button>
          </div>
        </div>
      )}

      {/* STEP 2: VISUAL PDF FIELD MAPPER */}
      {activeStep === 'MAPPER' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6">
          {/* Left Toolbar: Field Types */}
          <div className="lg:col-span-3 bg-white border border-slate-200 rounded-xl p-4 shadow-2xs space-y-4">
            <div>
              <h3 className="font-bold text-xs text-slate-900 uppercase tracking-wider">
                Field Toolbar
              </h3>
              <p className="text-[11px] text-slate-500">
                Click any control to place a coordinate box onto the PDF sheet.
              </p>
            </div>

            <div className="grid grid-cols-2 gap-2">
              {FIELD_TOOLBAR_ITEMS.map((item) => (
                <button
                  key={item.type}
                  onClick={() => handleAddField(item.type)}
                  className="flex items-center gap-2 p-2 rounded-lg border border-slate-200 hover:border-blue-500 hover:bg-blue-50/60 text-left transition-all text-xs font-medium text-slate-700 group"
                >
                  <span className="w-5 h-5 rounded-sm bg-slate-100 group-hover:bg-blue-100 flex items-center justify-center text-[10px] font-bold text-slate-600 group-hover:text-blue-700">
                    {item.icon}
                  </span>
                  <span className="truncate text-[11px]">{item.label}</span>
                </button>
              ))}
            </div>

            <div className="pt-3 border-t border-slate-100">
              <span className="text-[10px] font-bold text-slate-400 uppercase tracking-wider block mb-2">
                Active Fields ({fields.length})
              </span>
              <div className="max-h-48 overflow-y-auto space-y-1">
                {fields.map((f) => (
                  <div
                    key={f.id}
                    onClick={() => setSelectedFieldId(f.id)}
                    className={`flex items-center justify-between px-2.5 py-1.5 rounded-md text-xs cursor-pointer ${
                      selectedFieldId === f.id
                        ? 'bg-blue-600 text-white font-semibold'
                        : 'bg-slate-50 hover:bg-slate-100 text-slate-700'
                    }`}
                  >
                    <span className="truncate">{f.label}</span>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        removeSelectedField(f.id);
                      }}
                      className="p-1 hover:text-rose-300"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                ))}
              </div>
            </div>
          </div>

          {/* Center: Visual Canvas Sheet */}
          <div className="lg:col-span-6 bg-slate-100 border border-slate-300 rounded-xl p-4 flex flex-col items-center justify-start overflow-auto min-h-[640px]">
            <div className="w-full flex items-center justify-between pb-2 mb-2 text-xs text-slate-500 border-b border-slate-200">
              <span className="font-semibold">Interactive A4 Sheet Preview</span>
              <span className="text-[11px]">Click or drag boxes to adjust position</span>
            </div>

            {/* Simulated PDF Page with ratio 1 : 1.414 */}
            <div
              className="relative w-full max-w-[500px] aspect-[1/1.414] bg-white rounded-md shadow-lg border border-slate-300 select-none overflow-hidden"
              style={{
                backgroundImage: 'radial-gradient(#cbd5e1 1px, transparent 1px)',
                backgroundSize: '20px 20px',
              }}
            >
              {/* Standard Synthetic Header */}
              <div className="p-3 border-b border-slate-200 bg-slate-50/80">
                <div className="text-[9px] font-bold text-slate-800 tracking-wider">
                  GULF WAY ENTERPRISE DOCUMENT
                </div>
                <div className="text-xs font-bold text-blue-900">
                  {formName || 'FORM TITLE'}
                </div>
              </div>

              {/* Render placed fields as visual overlay boxes */}
              {fields.map((field) => {
                const isSelected = selectedFieldId === field.id;
                return (
                  <div
                    key={field.id}
                    onClick={() => setSelectedFieldId(field.id)}
                    style={{
                      left: `${field.x}%`,
                      top: `${field.y}%`,
                      width: `${field.width}%`,
                      height: `${field.height}%`,
                    }}
                    className={`absolute rounded-xs cursor-move flex items-center justify-between px-1.5 transition-all text-[9px] font-medium border ${
                      isSelected
                        ? 'bg-blue-500/25 border-blue-600 ring-2 ring-blue-500/40 text-blue-900 z-20'
                        : field.type === 'signature'
                        ? 'bg-amber-500/20 border-amber-600 text-amber-900'
                        : field.type === 'company_stamp'
                        ? 'bg-emerald-500/20 border-emerald-600 text-emerald-900'
                        : field.type === 'document_number'
                        ? 'bg-indigo-500/25 border-indigo-600 text-indigo-900 font-bold'
                        : 'bg-slate-200/80 border-slate-400 text-slate-800'
                    }`}
                  >
                    <span className="truncate font-semibold">{field.label}</span>
                    <Move className="w-2.5 h-2.5 opacity-60" />
                  </div>
                );
              })}

              {/* Bottom Watermark Strip */}
              <div className="absolute bottom-2 left-4 right-4 text-[7px] text-slate-400 border-t border-slate-200 pt-1 flex justify-between">
                <span>Verification QR & Stamp Location</span>
                <span>Page 1 of 1</span>
              </div>
            </div>
          </div>

          {/* Right Inspector: Configure Selected Field */}
          <div className="lg:col-span-3 bg-white border border-slate-200 rounded-xl p-4 shadow-2xs space-y-4">
            <h3 className="font-bold text-xs text-slate-900 uppercase tracking-wider">
              Field Inspector
            </h3>

            {selectedField ? (
              <div className="space-y-3 text-xs">
                <div>
                  <label className="block text-[11px] font-bold text-slate-600 mb-1">
                    Field Label
                  </label>
                  <input
                    type="text"
                    value={selectedField.label}
                    onChange={(e) => updateSelectedField({ label: e.target.value })}
                    className="w-full px-2.5 py-1.5 border border-slate-300 rounded-md font-medium"
                  />
                </div>

                <div>
                  <label className="block text-[11px] font-bold text-slate-600 mb-1">
                    Field Name (Variable Key)
                  </label>
                  <input
                    type="text"
                    value={selectedField.name}
                    onChange={(e) => updateSelectedField({ name: e.target.value })}
                    className="w-full px-2.5 py-1.5 border border-slate-300 rounded-md font-mono text-[11px]"
                  />
                </div>

                <div className="grid grid-cols-2 gap-2">
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-500 mb-0.5">
                      X Pos (%)
                    </label>
                    <input
                      type="number"
                      min={0}
                      max={100}
                      value={selectedField.x}
                      onChange={(e) => updateSelectedField({ x: Number(e.target.value) })}
                      className="w-full px-2 py-1 border border-slate-300 rounded-md"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-500 mb-0.5">
                      Y Pos (%)
                    </label>
                    <input
                      type="number"
                      min={0}
                      max={100}
                      value={selectedField.y}
                      onChange={(e) => updateSelectedField({ y: Number(e.target.value) })}
                      className="w-full px-2 py-1 border border-slate-300 rounded-md"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-500 mb-0.5">
                      Width (%)
                    </label>
                    <input
                      type="number"
                      min={5}
                      max={100}
                      value={selectedField.width}
                      onChange={(e) => updateSelectedField({ width: Number(e.target.value) })}
                      className="w-full px-2 py-1 border border-slate-300 rounded-md"
                    />
                  </div>
                  <div>
                    <label className="block text-[10px] font-semibold text-slate-500 mb-0.5">
                      Height (%)
                    </label>
                    <input
                      type="number"
                      min={2}
                      max={30}
                      value={selectedField.height}
                      onChange={(e) => updateSelectedField({ height: Number(e.target.value) })}
                      className="w-full px-2 py-1 border border-slate-300 rounded-md"
                    />
                  </div>
                </div>

                {selectedField.type === 'dropdown' && (
                  <div>
                    <label className="block text-[11px] font-bold text-slate-600 mb-1">
                      Options (comma separated)
                    </label>
                    <input
                      type="text"
                      value={(selectedField.options || []).join(', ')}
                      onChange={(e) =>
                        updateSelectedField({
                          options: e.target.value.split(',').map((s) => s.trim()),
                        })
                      }
                      placeholder="Option 1, Option 2, Option 3"
                      className="w-full px-2.5 py-1.5 border border-slate-300 rounded-md"
                    />
                  </div>
                )}

                {selectedField.type === 'signature' && (
                  <div>
                    <label className="block text-[11px] font-bold text-slate-600 mb-1">
                      Required Signer Role
                    </label>
                    <select
                      value={selectedField.signerRole || 'USER'}
                      onChange={(e) => updateSelectedField({ signerRole: e.target.value })}
                      className="w-full px-2.5 py-1.5 border border-slate-300 rounded-md"
                    >
                      <option value="USER">Applicant / Employee</option>
                      <option value="APPROVER">Official Manager / Approver</option>
                      <option value="SUPER_ADMIN">Managing Director</option>
                    </select>
                  </div>
                )}

                <div className="space-y-1.5 pt-2 border-t border-slate-100">
                  <label className="flex items-center gap-2 cursor-pointer">
                    <input
                      type="checkbox"
                      checked={selectedField.required}
                      onChange={(e) => updateSelectedField({ required: e.target.checked })}
                      className="rounded-sm text-blue-600"
                    />
                    <span className="font-semibold text-slate-700 text-xs">Mandatory / Required Field</span>
                  </label>
                </div>

                <div className="pt-3">
                  <button
                    onClick={() => removeSelectedField(selectedField.id)}
                    className="w-full py-1.5 bg-rose-50 hover:bg-rose-100 text-rose-700 border border-rose-200 rounded-md text-xs font-semibold flex items-center justify-center gap-1 transition-colors"
                  >
                    <Trash2 className="w-3.5 h-3.5" />
                    <span>Delete Field</span>
                  </button>
                </div>
              </div>
            ) : (
              <div className="py-12 text-center text-slate-400 text-xs">
                Select a field on the sheet or add one from the left toolbar to configure its coordinates and rules.
              </div>
            )}
          </div>
        </div>
      )}

      {/* STEP 3: LIVE TEST-FILL & PDF VALIDATION */}
      {activeStep === 'TEST' && (
        <div className="grid grid-cols-1 lg:grid-cols-12 gap-6 bg-white border border-slate-200 rounded-xl p-6 shadow-2xs">
          <div className="lg:col-span-5 space-y-4">
            <div>
              <h3 className="font-bold text-sm text-slate-900 flex items-center gap-2">
                <Play className="w-4 h-4 text-blue-600" />
                <span>Test Form Live Data-Entry</span>
              </h3>
              <p className="text-xs text-slate-500">
                Fill in simulated data to verify that coordinates, font sizes, QR codes and borders render accurately.
              </p>
            </div>

            <div className="space-y-3 max-h-[500px] overflow-y-auto pr-2">
              {fields
                .filter(
                  (f) =>
                    f.type !== 'document_number' &&
                    f.type !== 'qr_code' &&
                    f.type !== 'company_stamp'
                )
                .map((field) => (
                  <div key={field.id}>
                    <label className="block text-xs font-semibold text-slate-700 mb-1">
                      {field.label}
                    </label>
                    {field.type === 'textarea' ? (
                      <textarea
                        rows={2}
                        value={testFillValues[field.name] || ''}
                        onChange={(e) =>
                          setTestFillValues({ ...testFillValues, [field.name]: e.target.value })
                        }
                        placeholder={field.placeholder || 'Enter sample test value...'}
                        className="w-full text-xs px-3 py-1.5 border border-slate-300 rounded-lg"
                      />
                    ) : (
                      <input
                        type={field.type === 'number' ? 'number' : 'text'}
                        value={testFillValues[field.name] || ''}
                        onChange={(e) =>
                          setTestFillValues({ ...testFillValues, [field.name]: e.target.value })
                        }
                        placeholder={field.placeholder || `Sample ${field.label}`}
                        className="w-full text-xs px-3 py-1.5 border border-slate-300 rounded-lg"
                      />
                    )}
                  </div>
                ))}
            </div>

            <button
              onClick={handleRunTestPreview}
              disabled={isLoadingPreview}
              className="w-full py-2.5 bg-blue-600 hover:bg-blue-700 text-white rounded-lg text-xs font-bold transition-colors flex items-center justify-center gap-2"
            >
              <Sparkles className="w-4 h-4" />
              <span>{isLoadingPreview ? 'Synthesizing PDF...' : 'Re-render Test PDF Preview'}</span>
            </button>
          </div>

          <div className="lg:col-span-7 bg-slate-50 border border-slate-200 rounded-xl p-4 flex flex-col items-center justify-center min-h-[520px]">
            {previewPdfBase64 ? (
              <iframe
                src={previewPdfBase64}
                className="w-full h-[540px] rounded-lg border border-slate-300 shadow-sm"
                title="Live PDF Preview"
              />
            ) : (
              <div className="text-center text-slate-400 text-xs">
                {isLoadingPreview ? 'Generating test PDF...' : 'Click "Re-render Test PDF Preview" to inspect layout.'}
              </div>
            )}
          </div>
        </div>
      )}
    </div>
  );
};
